"""create table for users

Revision ID: 7aaf7e95e73d
Revises: ed86327b1d86
Create Date: 2023-02-12 18:12:02.538253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aaf7e95e73d'
down_revision = 'ed86327b1d86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
