"""create table for users

Revision ID: ed86327b1d86
Revises: ebbadd61c26b
Create Date: 2023-02-12 18:06:20.597833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed86327b1d86'
down_revision = 'ebbadd61c26b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
